"""001_initial_schema

Revision ID: 29d28e6d902c
Revises:
Create Date: 2026-02-13 15:27:53.503364

"""
from typing import Sequence, Union

from alembic import op

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29d28e6d902c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('lat', sa.Float(), nullable=False),
                    sa.Column('lon', sa.Float(), nullable=False),
                    sa.Column('time_window_start', sa.String(),
                              nullable=False),
                    sa.Column('time_window_end', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_table('optimization_results',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('original_route', sa.JSON(), nullable=False),
                    sa.Column('optimized_route', sa.JSON(), nullable=False),
                    sa.Column('improvement_percentage', sa.Float(),
                              nullable=False),
                    sa.Column('model_used', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    )
    op.create_index(op.f('ix_optimization_results_id'),
                    'optimization_results', ['id'], unique=False)
    op.create_table('routes',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('locations_order', sa.JSON(), nullable=False),
                    sa.Column('total_distance', sa.Float(), nullable=False),
                    sa.Column('total_time', sa.Float(), nullable=False),
                    sa.Column('total_cost', sa.Float(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    )
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.create_table('metrics',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('route_id', sa.String(), nullable=True),
                    sa.Column('model_name', sa.String(), nullable=False),
                    sa.Column('response_time_ms', sa.Integer(),
                              nullable=False),
                    sa.Column('quality_score', sa.Float(), nullable=False),
                    sa.Column('cost', sa.Float(), nullable=False),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['route_id'], ['routes.id'],
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    )

    op.create_index(op.f('ix_metrics_id'), 'metrics', ['id'], unique=False)
    op.create_index(op.f('ix_metrics_model_name'), 'metrics',
                    ['model_name'], unique=False)
    op.create_index(op.f('ix_metrics_route_id'), 'metrics',
                    ['route_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metrics_route_id'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_model_name'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_id'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_optimization_results_id'),
                  table_name='optimization_results')
    op.drop_table('optimization_results')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
